version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.1
    - 2.7.4
    - 2.8.1
  - dependency-name: cryptography
    versions:
    - 3.4.6
  - dependency-name: apache-airflow
    versions:
    - 2.0.0
    - 2.0.1
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
