language: python
python:
- '3.6'
install:
- pip install pipenv
- SLUGIFY_USES_TEXT_UNIDECODE=yes pipenv install --dev
script:
- pipenv run pylint manifold_airflow_dags -E
- pipenv run pytest


notifications:
  slack:
    rooms:
      - secure: SDncKtH2PvP4q1sJDL/m0oJNaE78Ye0S2yQGmVOE71/a0ShzKCzt+Pa6SaklKspdcrD7D1AtgwJGwkQhxaqXtDDRI4WyYjCIi2I7VHy5drnzEddtpAi4mPedoqEC8m6lQbsmKewQFq5uFCQYetp7YHV675B3noOnGbWw0t3s0UVn17XV7G2zk3a6l4H9Rj7dM9eSbcSTl+vWoHA93ZoQpId278ZV4cTbL0lXvhAueTM1FCKAZxArHMRa3UA4ocDsO9tqiKK96Gf4qzcVzYAhc9tW2Tx/9wjvsAAKxRpdWjQ5n1oMX+oAhSIocxn9p3ye8GZ5OwgB3acigPcKt8foc6SuYrX2Ppu/s3BdJz9AK/fiRdqtpEu1PiQAbsAdhatGh2OolvaymR9LQ4NVLk+xvctUANS5TeFEnIfEl73SxPwh844PznwKiTFSvN/XAd+39R1BNHJopGgJfzaObODgI8uKtqQA4UPVxyuB3PfWAqUGJKRecqu9yaGnQhqqZdyL+o4GXqWBdXaRXwdRHtmwpbFa71RnjyWttOIMKxQhKTVhOtcAuuu3qwj+Z7q7hrxMwkL/Xq4gJ5jbfzcWbN/Tik47YXLppIOYT+57i1QeQAokHarE5/0/RhBMwn9mWqcP77IE8h+FAMaVtdOQbbULYGluhpHgENXL9f/FIDEZp/A=
    on_success: always
    on_failure: always
